[package]
name = "lin_alg"
version = "1.0.0"
authors = ["David O'Connor <the_alchemist@fastmail.com>"]
description = "Vector, matrix, and quaternion operations for general purposes"
keywords = ["algebra", "vector", "matrix", "quaternion", "rendering"]
categories = [
    "algorithms",
    "mathematics",
    "algorithms",
    "no-std",
    "rendering",
]
repository = "https://github.com/David-OConnor/lin-alg"
documentation = "https://docs.rs/lin_alg"
readme = "README.md"
license = "MIT"
exclude = [".gitignore"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = { version = "^0.2.19", optional = true, default-features = false }

[features]
no_std = ["num-traits/libm"]

# The `computer_graphics` feature enables projection matrices,
# and other operations used in computer graphics.
computer_graphics = []